### PR TITLE
fix empty group not round bottom corner issue

### PR DESCRIPTION
**Pull request by kid1412621**

### CODE REVIEW

**Comment by kid1412621** [comment]
let me know if need to align code style regarding the imports

**Comment by Ashinch** [comment]
> let me know if need to align code style regarding the imports

Yes, Android Studio will also choose `*` to optimize the import.

**Comment by kid1412621** [comment]
> > let me know if need to align code style regarding the imports
> 
> Yes, Android Studio will also choose `*` to optimize the import.

sure, I've changed it.

**Comment by Ashinch** [comment]
There seems to be a regression

**Comment by kid1412621** [comment]
> 
> 
> There seems to be a regression

That's odd. I can only see this during animation. Let me check.

**Comment by kid1412621** [comment]
> 
> 
> There seems to be a regression

Hi @Ashinch, thx for point out. This caused by no article left in a group after hit "clear article". I added a feed count to check if the group is actually empty. Here is [the fix](https://github.com/Ashinch/ReadYou/pull/533).

Due to this, it helps me find another issue which is fever won't sync unsubscribed feeds. I'll later check on this.

**Comment by Ashinch** [comment]
> Due to this, it helps me find another issue which is fever won't sync unsubscribed feeds. I'll later check on this.

I think it's because I didn't compare and delete the local outdated feed with the feed on the cloud. Recently, I also found this problem when integrating Google Reader API.

I think I can solve it.

**Pull request merged**
