### PR TITLE
replace URL inputstream with okhttp inputstream in RssHelper

### PR DESCRIPTION
**Pull request by kzaemrio**
improve performance by:

1. replace URL inputstream with okhttp inputstream
2. share same okhttp client dispatcher with RssHelper and ImageLoader

### CODE REVIEW

**Comment by Ashinch** [comment]
Hi @kzaemrio 

Thank you very much for the pull request, I'm currently refactoring these codes on the `feature/optimize` branch, you may need to make some changes when it gets merged.

**Comment by kzaemrio** [comment]
Cool! 

Nice compose app

ps: please fix articleDao.insertIfNotExist first. It makes sync fail issue. Entries are already distincted by latestLink, maybe there is no need to insertIfNotExist

**Comment by Ashinch** [comment]
@kzaemrio Yes, I noticed that too.

**Comment by Ashinch** [comment]
Hi @kzaemrio 👋

Can you update `kzaemrio:main` branch, please?

The `Ashinch:main` branch recently got some new commits.

**Comment by kzaemrio** [comment]
Nice job! 🎉

**Comment by Ashinch** [comment]
Thank you! ❤️

**Comment by Ashinch** [comment]
#13

**Pull request merged**
