### PR TITLE
Add buttons to collapse and expand every group.

### PR DESCRIPTION
**Pull request by aualbert**
Closes https://github.com/Ashinch/ReadYou/issues/760 (partially).

<details>

Screenshot_20240612_163246

</details>

### CODE REVIEW

**Comment by Ashinch** [comment]
Hi, @aualbert 

Thank you so much for your contributions. I will review them recently, but I‘m not sure if all of them can be merged.

**Comment by Ashinch** [comment]
Hi, @aualbert 

I think we should follow the original UI and use only a single collapse/expand toggle button and keeping them aligned.

<details>
image
</details>

**Comment by aualbert** [comment]
> Hi, @aualbert 
> 
> I think we should follow the original UI and use only a single collapse/expand toggle button and keeping them aligned.
> 
> <details>
> image
> </details>

Sure!

**Comment by aualbert** [comment]
I we only keep one button, what should be its behavior if half of the groups are expanded ? This seems a bit strange to me. Perhaps https://github.com/Ashinch/ReadYou/issues/54 is the way to go.

**Comment by Ashinch** [comment]
I pushed some changes to https://github.com/aualbert/ReadYou/pull/1

**Pull request merged**
