### PR TITLE
feat(ui): long press on an item to show context menu

### LINKED ISSUE #611: Long press an item in article list to show context menu with actions
Actions:
- Toggle read
- Toggle starred
- Mark above as read (WIP)
- Mark below as read (WIP)
- Share

### PR DESCRIPTION
**Pull request by JunkFood02**
A walkaround or add-on before we implement #585 
Close #611 

To Do:

- [x] Mark above/below as read
- [x] Enter/exit transition for dropdown menu (optional)

### CODE REVIEW

**Comment by JunkFood02** [comment]
> By highlighting the item card, I mean the state when you hold your finger on it, which triggers the menu. But now, when you stop holding it, the bg color disappears - my idea is to make this display until the context menu is closed.

It's a bug and I just fixed it

> highlight the article that opened the context menu*.

Not sure about whether I have the energy to make another design for it, but I'll give it a try when I have time.

> But... maybe make it a bit easier? Place read/star/share in a grid

No, just follow the [guidelines](https://m3.material.io/components/menus/overview)

> shadows are ugly

Yes, blame google

**Comment by JunkFood02** [comment]
## Mark above/below as unread

After evaluating the existing code base and the current model of how we handle read status updating, I find it difficult to implement new logic to make the `markAsRead` method(s) accept an extra `after: Date`.

### Problems

- APIs are all written to mark as read `before` a certain date, modifying such APIs needs sigfinicant refactoring to the current Repositories, DAOs, and even remote API services
-  SQL queries is being used heavily for filtering, searching, and presenting the paged data to the UI layer. Writing new SQL queries, or adding new fields on existing queries is painful.

### Proposed Solution

In this PR, two new methods are added to the code base, `updateReadStatusByIdSet` in `AbstractRssRepository`, and `markAsReadFromListByDate` in `FlowViewModel`.

- `updateReadStatusByIdSet`

Just what its name suggests, bulk updating the read status by a `Set` of article id

- `markAsReadFromListByDate`

Filter the list before or after the given `Date`, map it to the set of article id, then call `updateReadStatusByIdSet`

### Considerations
- Ease of implementation: no structural changes made to code base, ~60 LoC
- Consistent with UI: Users are only presented with limited data, operations on the same paging data list won't bring unexpected behaviors, whether it's being filtered or/and being searched

### To-Do
- Bulk updating for FeverAPI (`updateReadStatusByIdSet`)

**Comment by JunkFood02** [comment]
It seems like that fever doesn't support bulk update of the read mark of multiple items, should we disable this feature on Fever accounts to avoid sync errors? @Ashinch

**Comment by Ashinch** [comment]
> It seems like that fever doesn't support bulk update of the read mark of multiple items, should we disable this feature on Fever accounts to avoid sync errors? @Ashinch 

We can mark them as read in turn on the background threads. Can leave this todo to me.

**Comment by Ashinch** [comment]
> It seems like that fever doesn't support bulk update of the read mark of multiple items, should we disable this feature on Fever accounts to avoid sync errors? @Ashinch

Hi, @JunkFood02 

#640 has been merged.

Usage: `rssService.get().batchMarkAsRead(articleIds, false)`

**Review by Ashinch — APPROVED** [review]
LGTM

**Pull request merged**
