### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
For your [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2088) (I saw the bot complain). Please integrate the screenshots (currently stored in `/screenshots`) and add your `zh` locale incl. the corresponding screenshots and description). For guidance, be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688).

### CODE REVIEW

**Comment by Ashinch** [comment]
Thanks for your Fastlane Cheat Sheet.

**Comment by IzzySoft** [comment]
Thanks for the fast merge! In case you missed the link: in the issuebot result: your app is currently [online in my repo](https://apt.izzysoft.de/fdroid/index/apk/me.ash.reader) (until it goes live with F-Droid; I usually remove apps after a 10 days overlap unless requested otherwise). Be welcome using [my badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there :wink:

**Comment by Ashinch** [comment]
I was worried about rejecting the review because of the automatic update feature, and just now I submitted the code to remove this feature.

**Comment by IzzySoft** [comment]
One possible answer are build flavors. So you can disable that feature for F-Droid (where it wouldn't work anyway) while keeping it for other places.

**Comment by Ashinch** [comment]
Do I need to public the signing key currently used by the Release?

Will F-Droid use Github Release or execute build it?

**Comment by IzzySoft** [comment]
F-Droid will build your app from the app's code and, when that succeeds, sign it with a key it creates dedicated to the app's applicationId – so no, you don't need to provide any signing stuff. Just for my repo the signed APK is needed as I have no build environment.

**Pull request merged**
