### PR TITLE
WIP: Some new features and fixes

### PR DESCRIPTION
**Pull request by aeghn**
- ~~Remember Feeds Postion~~ https://github.com/Ashinch/ReadYou/pull/519
- Ignore queryRssIcon exception
- ~~only swipe to remove artile with unread filter~~ https://github.com/Ashinch/ReadYou/pull/520

https://github.com/Ashinch/ReadYou/assets/51843252/07a76881-9102-4708-ba5a-51fc6de335fb

### CODE REVIEW

**Comment by aeghn** [comment]
I have also make some changes for
- Feeds sort support
- export starred items to a single json file
- support swipe guestures for switching article (based on #468 , I dropped my previous implements(on my dev branch) after I noticed there are a pr already here which is a better approach), swipe left and right for article switching and pull down for fetch full contents
- indicator support on the article page
- auto scroll to the new article position when you swipe to another article
- backward swipe support

**Comment by Ashinch** [comment]
Thanks for your work, I will take some time to review and merge them. For
another way of switching articles, I intend to provide multiple options
later, but not within the scope of this PR.

Best regards,
Ash

**Comment by aeghn** [comment]
> Thanks for your work, I will take some time to review and merge them.

Okay, please let me know if you think any code is not mature to merge or foolish, I'll be very happy to improve my kotlin skills. 

> For another way of switching articles, I intend to provide multiple options later, but not within the scope of this PR.

Yes, I hold the same opinion, I would wait for the #468 to be merged  and do some work  then.

**Comment by Ashinch** [comment]
> These do seem like they could be breaking changes, or otherwise need further testing - @Ashinch if you're considering taking these features on, maybe consider cutting the `0.9.9` release before merging this and #468? Then, more dedicated users can test these new features for a later `0.9.10` release.

You're right, #481 and #468 will not be merged until after 0.9.9 is released.

**Comment by aeghn** [comment]
I realized this PR is a little big, so I'm trying split it into some little PRs.

**Comment by Ashinch** [comment]
The pull request has already been split and merged, so it will be closed. If there are any remaining features, you can submit them separately.

**Pull request closed without merging**
