### PR TITLE
build(deps): bump up dependencies, compile sdk, and gradle version

### PR DESCRIPTION
**Pull request by JunkFood02**
## What did this pull request do?
- Migrate to [Compose BOM](https://developer.android.com/jetpack/compose/bom), and update Compose dependencies to Compose BOM 2023.10.01
- Update Compose compiler to 1.5.7 (requires Kotlin 1.9.21)
- Update Kotlin to 1.9.21
- Update a bunch of dependencies (hilt, coil, okhttp, room, accompanist, lifecycle)
- Update Android Gradle Plugin to 8.2.1, and Gradle to 8.0
- Update `compileSdk` to 34 (not `tragetSdk`)
- Changes are made to source to pass the lint check

> [!Note]
Potential breaking changes and bugs may probably occur during usage. Please test these changes carefully before merging this PR, or consider publishing an alpha release.

### CODE REVIEW

**Comment by mbestavros** [comment]
@JunkFood02 I'm going to cut `0.9.9` without this change, and then we can cut `0.9.10` with it included once you're satisfied it's stable (along with any other improvements that come along).

**Comment by mbestavros** [comment]
@JunkFood02 - when you have a moment, would you be willing to rebase this? We've gotten a lot of fixes merged recently, and I'd say Read You is in a fairly stable state at present. Might be a good time to evaluate a test APK for any obvious bugs that would be caused by the dependency bumps.

**Comment by Ashinch** [comment]
@mbestavros The highlight of version 0.9.12 is the integration of the GoogleReader API. This pull request might need to be delayed a bit and may require merging after the release of version 0.9.12. Once this pull request is merged, significant refactoring of the user interface code will be necessary to ensure proper functionality.

**Comment by JunkFood02** [comment]
> user interface code will be necessary to ensure proper functionality

I believe that we can only focus on those experimental APIs first, then gradually refactor the rest part of the code, since most Compose API are already stable. The main goal of this PR is to improve the performance issues which had been addressed in recent Compose updates.

**Pull request merged**
