### PR TITLE
[RFC] Swipe ReadingPage

### PR DESCRIPTION
**Pull request by boun**
Hi,

this is just a request for comments, no proper merge request. Anyway, I'd like to "infinite scroll" from article to article, so when I reach the bottom and continue scrolling, I reach the next article. I thought about different approaches to tackle that, this is the way I got it working. So now I have a NestedScrollConnection listening to scroll and fling events, that feeds a swipeable Modifier. The connection only consumes what is left over from its child views. That should only happen when the bottom (or top) of the page is reached. Everything is implemented as a modifer, to not clutter the ReadingPage code.

I chose to have a vertical swipe, as it feels the most natural to me. 

I'd appreciate a review.

What is still missing:
- Obviously: Remove the "DO NOT MERGE" commit (it creates a debug build with a red icon)

### CODE REVIEW

**Comment by Ashinch** [comment]
@boun Thank you for your explore, I've been refactoring the package structure lately and I'll spend some time going through this PR.

**Comment by Ashinch** [comment]
Hi @boun ,

I tried it out, and it feels great. 🤩 We're already very close to the Reeder 5 experience. Now, it seems like the only thing we're missing is a gesture-based interactive animation.

**Comment by boun** [comment]
So I have been using it for some time now and noticed one drawback: Choosing only unread in the article list, starting reading and then swiping up/down leads to unexpected behaviour. When swiping down, the previous article is marked read and therefore vanishes from the list. Swiping up again does hence not return to that previous article but to another unread If there is even one. I'll look into that.

About the animation: you mean an arrow indicating the article change? I have looked into the swiperefresh dependency that you are using for updating the reading list but that does not work for bottom swipes. It has been replaced by something in compose that I have not tried yet (but seems to support only top swipes). So it seems like rolling an own implementation is required.

**Comment by boun** [comment]
hi nvllz, thanks for the testing! indeed there were some glitches in the experience, but seems like @aeghn got that covered

**Comment by boun** [comment]
closing, superseded by #481

**Comment by boun** [comment]
o.k. did not read the whole thread in #481 so they wait for this branch to be merged ;-) I'll check what was done there and try to grab some time to get that to a decent state.

**Comment by boun** [comment]
@aeghn Easy, no problem at all. My open issues on the list were that swiping (no matter left/right or up/down) would mark the articles read, which in turn in "unread mode" would prevent swiping back there. Fixing that would require some significant changes in the way the model works (well or a quick dirty hack). So I was waiting for opinions from others (e.g. @Ashinch) here. Plus the problems reported by nvllz. The branch is an experimental playground to explore what works best, so feel free to take and improve, I dont have that much time on my hand right now.

**Comment by Ashinch** [comment]
I will be checking on this after the version 0.9.9 release.

**Comment by Ashinch** [comment]
Can you provide a new switch option in `Settings -> Color & Style -> Reading Page -> General (Horizontal Swipe to Next)` to enable it? I think it should be off by default.

**Comment by boun** [comment]
Yup, will do

**Comment by boun** [comment]
Superseeded

**Pull request closed without merging**
